feat: User 기능 구현
tronze/capstone-design-I pull request #5
Opened 2024-11-07 10:15 UTC by rainshowerr

User 관련 기능을 구현하였습니다.
User 모델에서 role 필드를 제거 + 회원가입/로그인 시 jwt 페이로드에 uid를 함께 반환하도록 수정했습니다.

2024-11-07 18:57 UTC, tronze requested changes
고생하셨습니다! 일단 코멘트 읽어보시고 궁금하신 부분이나 제가 파악하지 못한 부분이 있다면 알려주시길 바라요. 그 후에 수정이 필요한 부분을 파악하여 수정 진행해보면 어떨까 생각합니다.

2024-11-07 18:57 UTC, tronze commented on backend/account/tests/test_profile.py
> +    def test_get(self):
유저 정보를 대조해볼 필요는 없을까요?

2024-11-07 18:57 UTC, tronze commented on backend/account/tests/test_profile.py
> +        updated_user = User.objects.all().get(email=self.moke_user.email)
그냥 `User.objects.get(email=self.mock_user.email)`이면 충분합니다!
물론 저렇게 작성하셔도 구동에는 아무 지장이 없습니다.

2024-11-07 18:57 UTC, tronze commented on backend/account/tests/test_profile.py
> +        self.assertNotEqual("logintest", updated_user.password)
이 코드는 무슨 역할을 하는지 잘 모르겠어요.
혹시 암호화된 비밀번호를 저장되는지 체크하기 위한 의도인가요?
아니라면 password를 patch할 때 암호화 되어 저장되는데 NotEqual를 테스트하는 이유가 궁금합니다.

2024-11-07 18:57 UTC, tronze commented on backend/backend_module/custom_exception_handler.py
> +                return Response({"email": "중복된 이메일입니다. 다른 이메일을 입력해주세요.", "status_code": status.HTTP_400_BAD_REQUEST}, status=status.HTTP_400_BAD_REQUEST)
프론트 측에서 에러를 파싱할 때 어떤 류의 에러인지 알 수 있으면 좋을 것 같습니다.
예를 들어
```python
{
  'code': 1 # 요청값 에러
  'detail': '중복된 이메일입니다',
  'field': 'email' # code가 1일 때만 같이 보내지는 필드
  'status_code': 400,
}
```

이렇게 하면 프론트 측에서 코드를 기준으로 에러를 파싱하고 원하는 형태를 만들기 위해서 더 편하게 활용할 수 있지 않을까 생각이 듭니다.

2024-11-07 18:57 UTC, tronze commented on backend/account/views.py
> +        instance.is_active = False
여기서 `is_active`만 `False`로 조정하면 같은 이메일로 재가입 할 때 이메일이 중복되기 때문에 문제가 됩니다. 그렇기 때문에 `email`, `name` 등도 난수로 값을 변경하여 데이터는 남기되 같은 이메일로 재가입할 때 문제가 없도록 하는 것이 어떨까요? 또 비번도 `set_unusable_password()`를 통해 비번도 사용하지 못하는 값으로 변경해 두는 것을 추천합니다.

2024-11-07 18:57 UTC, tronze commented on backend/account/tests/test_registration.py
전반적으로 요청이 Bad Request로 반환 됐을 때 프론트 측에서 받는 형태가 조정 되면 좋을 것 같아요. 또 이유가 무엇인지 파싱하기 편하면 더 좋을 것 같습니다. `exception_handler` 부분에서 어떻게 조정되면 좋을지에 대해서 예시로 적어놨습니다.

2024-11-08 02:00 UTC, rainshowerr commented on backend/account/tests/test_profile.py
> +    def test_get(self):
다른 유저의 정보를 보지 못하게 해야 한다는 말씀이실까요?

2024-11-08 02:00 UTC, rainshowerr commented on backend/account/tests/test_profile.py
> +        updated_user = User.objects.all().get(email=self.moke_user.email)
관련 코드들 전부 수정해두겠습니다!!

2024-11-08 02:00 UTC, rainshowerr commented on backend/account/tests/test_profile.py
> +        self.assertNotEqual("logintest", updated_user.password)
넵 혹시 암호화 안되고 그냥 평문으로 저장될까봐 넣어뒀어요!

2024-11-08 02:01 UTC, rainshowerr commented on backend/backend_module/custom_exception_handler.py
> +                return Response({"email": "중복된 이메일입니다. 다른 이메일을 입력해주세요.", "status_code": status.HTTP_400_BAD_REQUEST}, status=status.HTTP_400_BAD_REQUEST)
알겠습니다!!

2024-11-08 02:04 UTC, rainshowerr commented on backend/account/views.py
> +        instance.is_active = False
수정해두겠습니다!!

2024-11-08 02:04 UTC, rainshowerr commented on backend/account/tests/test_registration.py
넵 알겠습니당

2024-11-08 06:10 UTC, rainshowerr commented on backend/account/views.py
> +        instance.is_active = False
name은 유니크 조건이 없어서 email과 password만 처리해뒀습니다!

2024-11-08 08:31 UTC, tronze commented on backend/account/tests/test_registration.py
@tronze 가 고민해보기로 함

2024-11-08 08:31 UTC, tronze commented on backend/backend_module/custom_exception_handler.py
> +                return Response({"email": "중복된 이메일입니다. 다른 이메일을 입력해주세요.", "status_code": status.HTTP_400_BAD_REQUEST}, status=status.HTTP_400_BAD_REQUEST)
@tronze 가 고민해보는 걸루

2024-11-08 08:34 UTC, tronze approved these changes
고생하셨습니다

2024-11-08 08:34 UTC, merged